# app/agents/draft_agent.py
import logging
from datetime import datetime
from app.utils.gemini_client import call_gemini, DEFAULT_MODEL


class DraftAgent:
    """
    Generates a blog draft from the outline + research brief.
    Produces markdown text.
    """

    def __init__(self, model: str = DEFAULT_MODEL):
        self.model = model

    def run(
        self,
        outline_markdown: str,
        research_brief: str,
        topic: str,
        tone: str = "informative",
        length: str = "short"
    ) -> str:

        prompt = (
            "You are a clear, concise blog writer.\n"
            "Write a well-structured blog article using the outline and research brief below.\n\n"
            f"Topic: {topic}\n"
            f"Tone: {tone}\n"
            f"Length preference: {length}\n\n"
            f"Research Brief:\n{research_brief}\n\n"
            f"Outline:\n{outline_markdown}\n\n"
            "Write the final blog in markdown format.\n"
            "- Each heading should have 2–4 short paragraphs.\n"
            "- Keep intro and conclusion crisp.\n"
            "- Do NOT produce extra explanations or commentary."
        )

        logging.info("DraftAgent: calling Gemini to produce blog draft")

        # No max_tokens, no max_output_tokens – the new API rejects them.
        draft = call_gemini(prompt, model=self.model)

        header = f"<!-- Generated by MiniBlogForge on {datetime.utcnow().isoformat()} -->\n\n"
        return header + draft.strip()
